export default {
  INIT: 'INIT',
  ADD_FAVORITE: 'ADD_FAVORITE',
  ADD_CART: 'ADD_CART',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  REMOVE_CART: 'REMOVE_CART',
  CHANGE_COUNT: 'CHANGE_COUNT',
  FILTER: 'FILTER',
  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  CLEAR_CART: 'CLEAR_CART',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
};
